# Generated by Django 2.0.7 on 2019-07-08 15:29

from django.db import migrations, models
from frontend.models import Person


def insert_users(apps, schema_editor):
    Person(1, 'john', 'doe').save()
    Person(2, 'eric', 'clapton').save()
    Person(3, 'clark', 'kent').save()
    Person(4, 'bruce', 'wayne').save()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=32)),
                ('lastname', models.CharField(max_length=32)),
            ],
        ),
        migrations.RunPython(insert_users),
    ]
